name: Publish to NPM

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Publish to NPM when missing
      uses: geoblink/publish-to-npm@v1.0.2
